Parameters:
  S3BucketName:
    Type: String
    Default: muhtashim-doc-example-bucket
    Description: S3BucketName
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName